const addStyle=href=>{const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link)};addStyle('hero-bottom-adjust.css');addStyle('mobile.css');addStyle('hero-booking-layout.css');let tripType='round';
function setMinimumDate(){const today=new Date().toISOString().slice(0,10);const depart=document.querySelector('#depart');const returning=document.querySelector('#return');if(depart)depart.min=today;if(returning)returning.min=today;depart?.addEventListener('change',()=>{if(returning){returning.min=depart.value||today;if(returning.value&&returning.value<depart.value)returning.value=depart.value}})}
function chooseTrip(button){tripType=button.dataset.trip;document.querySelectorAll('[data-trip]').forEach(item=>item.classList.toggle('active',item===button));const field=document.querySelector('#return-field');const input=document.querySelector('#return');if(field&&input){const oneWay=tripType==='one';field.hidden=oneWay;input.disabled=oneWay;if(oneWay)input.value=''}}
const PASSENGER_TYPES=[{key:'adult',label:'adult',min:1},{key:'child',label:'child'},{key:'infant',label:'infant'},{key:'senior',label:'senior citizen'},{key:'pwd',label:'person with disability'},{key:'ofw',label:'overseas Filipino worker'}],MAX_PAX=9,CABIN_BAGGAGE={Economy:{checked:20,carryOn:7},Comfort:{checked:25,carryOn:10},Business:{checked:30,carryOn:12}},EXTRA_KG_RATE=300,EXTRA_KG_STEP=5,MAX_EXTRA_KG=60,DEFAULT_PASSENGERS={adult:1,child:0,infant:0,senior:0,pwd:0,ofw:0},DEFAULT_BAGGAGE={extraKg:0,cost:0,rate:EXTRA_KG_RATE,includedKg:0},SEARCH_DEFAULTS={from:'Manila (MNL)',to:'Tokyo (NRT)',depart:'Flexible dates',returning:'',cabin:'Economy',tripType:'round',passengers:DEFAULT_PASSENGERS,baggage:DEFAULT_BAGGAGE};let passengerCounts={...DEFAULT_PASSENGERS},extraKg=0;
const cabinRule=cabin=>CABIN_BAGGAGE[cabin]||CABIN_BAGGAGE.Economy;
const extraBaggageCost=()=>extraKg*EXTRA_KG_RATE;
const paxLimit=key=>key==='infant'?Math.min(MAX_PAX,passengerCounts.adult):MAX_PAX;
const paxFloor=key=>PASSENGER_TYPES.find(type=>type.key===key).min||0;
function totalTravelers(passengers=passengerCounts){return PASSENGER_TYPES.reduce((sum,type)=>sum+(Number(passengers[type.key])||0),0)}
function describePassengers(passengers=passengerCounts){const parts=PASSENGER_TYPES.map(type=>[type.label,Number(passengers[type.key])||0]).filter(([,count])=>count>0).map(([label,count])=>`${count} ${label}${count>1?'s':''}`);return parts.length?parts.join(', '):'no travelers'}
function getCabin(){return document.querySelector('input[name="cabin"]:checked')?.value||'Economy'}
function renderBaggage(){const cabin=getCabin(),rule=cabinRule(cabin),travelers=totalTravelers(),hint=document.querySelector('#bgg-hint'),count=document.querySelector('#bgg-count'),total=document.querySelector('#bgg-total'),minus=document.querySelector('#bgg-minus'),plus=document.querySelector('#bgg-plus');if(hint)hint.textContent=`${cabin} includes ${rule.checked} kg checked and ${rule.carryOn} kg carry-on per traveler, ${rule.checked*travelers} kg for ${travelers} traveler${travelers>1?'s':''}.`;if(count)count.textContent=`${extraKg} kg`;if(minus)minus.disabled=extraKg<=0;if(plus)plus.disabled=extraKg>=MAX_EXTRA_KG;if(total)total.textContent=extraKg?`Extra baggage ${extraKg} kg x PHP ${EXTRA_KG_RATE} = PHP ${extraBaggageCost().toLocaleString()}`:'No extra baggage added'}
function renderPassengers(){PASSENGER_TYPES.forEach(({key})=>{const count=passengerCounts[key],min=paxFloor(key),max=paxLimit(key);document.querySelector(`[data-count="${key}"]`).textContent=count;document.querySelectorAll(`[data-pax="${key}"]`).forEach(button=>button.disabled=Number(button.dataset.step)<0?count<=min:count>=max)});const label=document.querySelector('#pax-trigger-text'),travelers=totalTravelers(),cabin=getCabin();if(label)label.textContent=`${travelers} traveler${travelers>1?'s':''}, ${cabin}${extraKg?`, +${extraKg} kg`:''}`;renderBaggage()}
function setPassenger(key,step){const type=PASSENGER_TYPES.find(item=>item.key===key);if(!type)return;passengerCounts[key]=Math.min(paxLimit(key),Math.max(paxFloor(key),passengerCounts[key]+step));if(key==='adult'){if(passengerCounts.infant>passengerCounts.adult)passengerCounts.infant=passengerCounts.adult}renderPassengers()}
function setExtraKg(step){extraKg=Math.min(MAX_EXTRA_KG,Math.max(0,extraKg+step*EXTRA_KG_STEP));renderPassengers()}
function setPassengerPanel(open){const panel=document.querySelector('#pax-panel'),trigger=document.querySelector('#pax-trigger');if(!panel||!trigger)return;panel.hidden=!open;trigger.setAttribute('aria-expanded',String(open))}
function initPassengerPicker(){const panel=document.querySelector('#pax-panel'),trigger=document.querySelector('#pax-trigger');if(!panel||!trigger)return;passengerCounts={...DEFAULT_PASSENGERS};extraKg=0;trigger.addEventListener('click',()=>setPassengerPanel(panel.hidden));document.querySelector('#pax-done')?.addEventListener('click',()=>{setPassengerPanel(false);trigger.focus()});panel.addEventListener('click',event=>{const button=event.target.closest('.step-btn');if(button)setPassenger(button.dataset.pax,Number(button.dataset.step))});document.querySelector('#bgg-plus')?.addEventListener('click',()=>setExtraKg(1));document.querySelector('#bgg-minus')?.addEventListener('click',()=>setExtraKg(-1));document.querySelectorAll('input[name="cabin"]').forEach(input=>input.addEventListener('change',renderPassengers));document.addEventListener('click',event=>{if(!panel.hidden&&!panel.contains(event.target)&&!trigger.contains(event.target))setPassengerPanel(false)});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!panel.hidden)setPassengerPanel(false)});renderPassengers()}
function runSearch(){const passengers={...passengerCounts},warning=document.querySelector('#pax-warning');if(passengers.infant>passengers.adult){warning.textContent='Each infant needs an accompanying adult. Add an adult or remove an infant.';warning.hidden=false;setPassengerPanel(true);return}warning.hidden=true;const from=document.querySelector('#from')?.value||SEARCH_DEFAULTS.from,to=document.querySelector('#to')?.value||SEARCH_DEFAULTS.to,depart=document.querySelector('#depart')?.value||SEARCH_DEFAULTS.depart,returning=document.querySelector('#return')?.value||'',cabin=getCabin(),baggage={extraKg,cost:extraBaggageCost(),rate:EXTRA_KG_RATE,includedKg:cabinRule(cabin).checked*totalTravelers(passengers)};const search={from,to,depart,returning,cabin,passengers,baggage,tripType};localStorage.setItem('aeroviaSearch',JSON.stringify(search));window.location.href='results.html'}
function getSearch(){let saved;try{saved=JSON.parse(localStorage.getItem('aeroviaSearch'))}catch{}return {...SEARCH_DEFAULTS,...saved,passengers:{...DEFAULT_PASSENGERS,...saved?.passengers},baggage:{...DEFAULT_BAGGAGE,...saved?.baggage}}}
function renderResults(){const summary=document.querySelector('#results-summary');if(!summary)return;const search=getSearch(),travelers=totalTravelers(search.passengers),baggage={...DEFAULT_BAGGAGE,...search.baggage},extraCost=Number(baggage.cost)||0,rule=cabinRule(search.cabin),dates=search.tripType==='one'?search.depart:`${search.depart} to ${search.returning||'Flexible return'}`;summary.textContent=`${search.from} to ${search.to} | ${dates} | ${search.cabin} | ${travelers} traveler${travelers>1?'s':''} (${describePassengers(search.passengers)})${extraCost?` | +${baggage.extraKg} kg extra baggage`:''}`;const multiplier=search.cabin==='Business'?2.45:search.cabin==='Comfort'?1.45:1;document.querySelectorAll('.flight-option').forEach((card,index)=>{card.querySelector('[data-route]').textContent=`${search.from.split(' ')[0]} to ${search.to.split(' ')[0]}`;const fare=Math.round(([8990,9740,10380][index]||8990)*multiplier),subtotal=fare*travelers,total=subtotal+extraCost;const info=card.querySelector('[data-baggage]');if(info)info.textContent=`${rule.checked} kg checked and ${rule.carryOn} kg carry-on per traveler${extraCost?` | +${baggage.extraKg} kg extra baggage, PHP ${extraCost.toLocaleString()}`:''}`;const lines=['<small>per traveler</small>'];if(travelers>1)lines.push(`<small>PHP ${subtotal.toLocaleString()} for ${travelers} travelers</small>`);if(extraCost)lines.push(`<small>PHP ${extraCost.toLocaleString()} extra baggage</small><small>PHP ${total.toLocaleString()} grand total</small>`);card.querySelector('.fare').innerHTML=`PHP ${fare.toLocaleString()}${lines.join('')}`;card.querySelector('button').addEventListener('click',()=>chooseFlight(fare,total,card.querySelector('.route-time').textContent))})}
function chooseFlight(fare,total,time){const search=getSearch(),passengers={...DEFAULT_PASSENGERS,...search.passengers},travelers=totalTravelers(passengers),reference=`AER${Math.floor(100000+Math.random()*900000)}`,grandTotal=total??fare*travelers+(Number(search.baggage?.cost)||0);localStorage.setItem('aeroviaBooking',JSON.stringify({...search,passengers,baggage:{...DEFAULT_BAGGAGE,...search.baggage},travelers,fare,total:grandTotal,time,reference}));window.location.href='passenger-details.html'}
const DEFAULT_CONTACT={firstName:'',lastName:'',email:'',phone:''},CONTACT_FIELDS=[['firstName','first'],['lastName','last'],['email','email'],['phone','phone']],REACHABLE_FIELDS=CONTACT_FIELDS.filter(([key])=>key==='email'||key==='phone'),EMAIL_PATTERN=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
function readBooking(){try{const parsed=JSON.parse(localStorage.getItem('aeroviaBooking'));return parsed&&typeof parsed==='object'?parsed:null}catch{return null}}
function writeBooking(booking){localStorage.setItem('aeroviaBooking',JSON.stringify(booking))}
function contactName(contact){return [contact?.firstName,contact?.lastName].map(part=>String(part||'').trim()).filter(Boolean).join(' ')}
function bookingView(booking){const passengers={...DEFAULT_PASSENGERS,...booking.passengers},travelers=booking.travelers||totalTravelers(passengers),rule=cabinRule(booking.cabin),baggage={...DEFAULT_BAGGAGE,...booking.baggage},extraCost=Number(baggage.cost)||0,subtotal=Number(booking.fare||0)*travelers,total=booking.total||subtotal+extraCost,includedKg=baggage.includedKg||rule.checked*travelers,dates=booking.tripType==='one'?booking.depart:`${booking.depart||'Flexible dates'} to ${booking.returning||'Flexible return'}`;return{passengers,travelers,rule,baggage,extraCost,subtotal,total,includedKg,dates,contact:{...DEFAULT_CONTACT,...booking.contact}}}
function baggageSentence(view){const base=`${view.rule.checked} kg checked and ${view.rule.carryOn} kg carry-on per traveler, ${view.includedKg} kg included`;return view.extraCost?`${base} | +${view.baggage.extraKg} kg extra baggage, PHP ${view.extraCost.toLocaleString()}`:base}
function itineraryLines(booking){const view=bookingView(booking),lines=[`<strong>${booking.reference} confirmed</strong>`,`${booking.from} to ${booking.to}`,`${booking.depart} | ${booking.time}`,`PHP ${Number(booking.fare||0).toLocaleString()} per traveler | ${booking.cabin}`,`${view.travelers} traveler${view.travelers>1?'s':''}: ${describePassengers(view.passengers)}`,baggageSentence(view)];if(view.extraCost)lines.push(`Extra checked baggage ${view.baggage.extraKg} kg: PHP ${view.extraCost.toLocaleString()}`);lines.push(view.extraCost?`PHP ${view.subtotal.toLocaleString()} fare + PHP ${view.extraCost.toLocaleString()} baggage = PHP ${view.total.toLocaleString()} total`:`PHP ${view.total.toLocaleString()} total`);if(contactName(view.contact))lines.push(`Lead passenger: ${contactName(view.contact)}`);if(view.contact.email)lines.push(`Email: ${view.contact.email}`);if(view.contact.phone)lines.push(`Phone: ${view.contact.phone}`);return lines}
function validateContact(contact,fields=CONTACT_FIELDS){const errors={},first=String(contact.firstName||'').trim(),last=String(contact.lastName||'').trim(),email=String(contact.email||'').trim(),phone=String(contact.phone||'').trim(),wants=key=>fields.some(([name])=>name===key);if(wants('firstName')&&!first)errors.firstName="Enter the lead passenger's first name.";if(wants('lastName')&&!last)errors.lastName="Enter the lead passenger's last name.";if(wants('email')){if(!email)errors.email='Enter an email address for your confirmation.';else if(!EMAIL_PATTERN.test(email))errors.email='That email address does not look right.'}if(wants('phone')){if(!phone)errors.phone='Enter a mobile number we can reach you on.';else if(phone.replace(/\D/g,'').length<7)errors.phone='That phone number looks too short.'}return errors}
function readContactForm(prefix,fields=CONTACT_FIELDS){const value=id=>String(document.querySelector(`#${prefix}-${id}`)?.value||'').trim();return Object.fromEntries(fields.map(([key,id])=>[key,value(id)]))}
function paintFieldErrors(prefix,errors,alert){CONTACT_FIELDS.forEach(([key,id])=>{const message=errors[key]||'',input=document.querySelector(`#${prefix}-${id}`),slot=document.querySelector(`#${prefix}-err-${id}`);if(input){input.setAttribute('aria-invalid',message?'true':'false');if(message)input.setAttribute('aria-describedby',`${prefix}-err-${id}`);else input.removeAttribute('aria-describedby')}if(slot)slot.textContent=message});const count=Object.keys(errors).length;if(alert){alert.textContent=count?`Please correct ${count} field${count>1?'s':''} below.`:'';alert.classList.toggle('show',count>0)}return!count}
function initPassengerDetails(){const form=document.querySelector('#pd-form'),empty=document.querySelector('#pd-empty'),review=document.querySelector('#pd-review');if(!form||!empty||!review)return;const booking=readBooking();if(!booking||!booking.reference){empty.hidden=false;form.hidden=true;review.hidden=true;const back=document.querySelector('#pd-form + .notice');if(back)back.hidden=true;return}const view=bookingView(booking),set=(selector,text)=>{const el=document.querySelector(selector);if(el)el.textContent=text};set('#pd-reference',booking.reference);set('#pd-route',`${booking.from} to ${booking.to}`);set('#pd-dates',view.dates);set('#pd-time',booking.time||'Flexible dates');set('#pd-cabin',booking.cabin);set('#pd-pax',`${view.travelers} traveler${view.travelers>1?'s':''} (${describePassengers(view.passengers)})`);set('#pd-bag',baggageSentence(view));set('#pd-fare',`PHP ${Number(booking.fare||0).toLocaleString()}`);set('#pd-total',`PHP ${view.total.toLocaleString()}`);CONTACT_FIELDS.forEach(([key,id])=>{const input=document.querySelector(`#pd-${id}`);if(input)input.value=view.contact[key]||''});review.hidden=false;form.addEventListener('submit',event=>{event.preventDefault();confirmBooking()})}
function confirmBooking(){const booking=readBooking();if(!booking||!booking.reference)return;const contact=readContactForm('pd');if(!paintFieldErrors('pd',validateContact(contact),document.querySelector('#pd-alert')))return;writeBooking({...booking,contact});window.location.href=`manage.html?confirmation=${booking.reference}`}
function renderContactEditor(booking){const editor=document.querySelector('#contact-editor');if(!editor)return;const contact={...DEFAULT_CONTACT,...booking.contact},email=document.querySelector('#ce-email'),phone=document.querySelector('#ce-phone'),name=document.querySelector('#ce-name');if(email)email.value=contact.email;if(phone)phone.value=contact.phone;if(name)name.textContent=contactName(contact)||'Not provided yet';editor.hidden=false}
function saveContact(){const booking=readBooking(),editor=document.querySelector('#contact-editor'),status=document.querySelector('#ce-status');if(!booking||!booking.reference||!editor)return;const contact={...DEFAULT_CONTACT,...booking.contact,...readContactForm('ce',REACHABLE_FIELDS)};if(!paintFieldErrors('ce',validateContact(contact,REACHABLE_FIELDS),null)){if(status){status.textContent='Please correct the highlighted fields.';status.className='form-status bad'}return}writeBooking({...booking,contact});if(status){status.textContent='Contact details updated.';status.className='form-status ok'}showBooking()}
function showBooking(){const reference=document.querySelector('#reference')?.value.trim().toUpperCase(),surname=document.querySelector('#surname')?.value.trim(),result=document.querySelector('#booking-result'),editor=document.querySelector('#contact-editor'),booking=readBooking();if(!booking||reference!==booking.reference||!surname){if(editor)editor.hidden=true;result.textContent='We could not find that booking. Check your reference and last name, then try again.';result.style.display='block';result.style.background='#fff1df';result.style.color='#8a4d00';return}result.innerHTML=itineraryLines(booking).join('<br>');result.style.display='block';result.style.background='#e6f5eb';result.style.color='#175b37';renderContactEditor(booking)}
function initDestinationFilter(){const filter=document.querySelector('#region-filter');if(!filter)return;filter.addEventListener('change',()=>document.querySelectorAll('.destination-card').forEach(card=>card.hidden=filter.value!=='All destinations'&&card.dataset.region!==filter.value))}
function startHeroSlider(){const slides=[...document.querySelectorAll('.hero-slide')];if(slides.length<2)return;let active=0;setInterval(()=>{slides[active].classList.remove('active');active=(active+1)%slides.length;slides[active].classList.add('active')},5200)}
function separateHeroBooking(){const hero=document.querySelector('.hero'),booking=hero?.querySelector('.booking');if(hero&&booking)hero.after(booking)}
document.addEventListener('DOMContentLoaded',()=>{separateHeroBooking();setMinimumDate();initPassengerPicker();initPassengerDetails();renderResults();initDestinationFilter();startHeroSlider();document.querySelectorAll('[data-trip]').forEach(button=>button.addEventListener('click',()=>chooseTrip(button)));const confirmation=new URLSearchParams(location.search).get('confirmation');const hint=document.querySelector('#search-hint');if(confirmation&&hint)hint.textContent=`Your booking reference is ${confirmation}. Enter it with your last name to view your itinerary.`})
